- app/assets/javascripts/scorm_course.js
- app/assets/stylesheets/scorm_course.scss
- app/controllers/api/courses_controller.rb
- app/controllers/scorm_course_controller.rb
- app/helpers/scorm_course_helper.rb
- app/services/scorm_cloud_service.rb
- client/js/actions/scorm.js
- client/js/components/scorm/course.jsx
- client/js/components/scorm/courses_list.jsx
- client/js/components/scorm/scorm_index.jsx
- client/js/middleware/redirect.js
- client/js/reducers/scorm.js
- config/application.rb
- config/routes.rb
- spec/controllers/api/courses_controller_spec.rb
- spec/services/scorm_cloud_service_spec.rb
Moves Scorm Coud api logic to it's own service object
> Add Scorm Cloud Service

- app/controllers/scorm_course_controller.rb
- app/services/scorm_cloud_service.rb
- client/js/components/scorm/course.jsx
- config/routes.rb
Adds ability to import scorm package as canvas assignment
> Import assignment

- app/controllers/scorm_course_controller.rb
- app/models/registration.rb
- app/services/scorm_cloud_service.rb
- db/migrate/20161109185759_add_registration__postback_password.rb
- db/migrate/20161110214431_encrypt.rb
- db/schema.rb
- spec/controllers/scorm_course_controller_spec.rb
* Authenticate scorm cloud course launch 
* Authenticate scorm cloud grade postback
> Scorm cloud auth

- app/controllers/exports_controller.rb
- app/views/exports/attendances.csv.erb
- client/js/attendance/actions/attendance.js
- client/js/attendance/store/configure_store.js
- client/js/middleware/download.js
- config/routes.rb
- package.json
- yarn.lock
> Old exports method

- .hound.yml
- package.json
Remove eslint from package.json as it is in client/package.json
> Fail hound on violations.

- client/js/scorm/components/common/file_upload.jsx
on change event doesnt fire unless the name of the file changes
> fixes issue uploading two of the same file in a row

- client/js/scorm/actions/scorm.js
- client/js/scorm/components/scorm/scorm_index.jsx
- client/js/scorm/reducers/scorm.js
- db/seeds.rb
- lib/tasks/lti.rake
if you delete assignments in scorm it deletes them from canvas, and if you delete them from canvas it deletes them from scorm
> keep canvas assignments and scorm assignment in sync [#134403191]

- app/views/exports/attendances.csv.erb
Should fix &quot; from showing up all over the CSV if names have the format Firstname, Lastname
> Splits the name if a comma is found, re-adds it for the row

- app/controllers/api/assigned_exams_controller.rb
- app/controllers/api/download_status_controller.rb
- app/controllers/download_status_controller.rb
- app/models/dowload_status.eb
- client/js/attendance/actions/attendance.js
- client/js/middleware/download.js
- client/js/proctor/actions/exams.js
- client/js/proctor/components/common/download_svg.jsx
- client/js/proctor/components/exam_distribution/_exam_distribution.jsx
- client/js/proctor/components/exam_distribution/student_assign.jsx
- client/js/proctor/store/configure_store.js
- config/routes.rb
- db/migrate/20170103192743_add_center_name.rb
- db/schema.rb
@BenHSmith13 or @dittonjs When you have some time look this over please.
> Csv downloader

- client/js/test_administration/components/exam_assignment_list/confirm_take_exam.jsx
- client/js/test_administration/components/exam_assignment_list/confirm_take_exam.spec.jsx
- client/js/test_administration/components/exam_assignment_list/message_instructor.jsx
- client/js/test_administration/components/exam_assignment_list/popup_menu.jsx
- client/js/test_administration/components/exam_assignment_list/proctor_code.jsx
> Confirm test

- client/js/proctor/actions/exams.js
- client/js/proctor/components/exam_distribution/_exam_distribution.jsx
- client/js/proctor/components/exam_distribution/_exam_distribution.spec.jsx
- client/js/proctor/reducers/exams.js
clear the state when we go back
> Fix state again

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/production.rb
- config/logging.example.yml
* move asset gems into dev folder, since they require extra things to be installed on the server.
* make sure dir where webpack build dumps stuff is created, but ignore the contents.
> production fixes

- client/js/exams/components/exam_list/_exam_list.jsx
- client/js/exams/components/exam_list/_exam_list.spec.jsx
- client/js/exams/components/exam_list/exam_list_item.jsx
- client/js/test_administration/actions/exam_requests.js
- client/js/test_administration/components/exam_request_list/_exam_request_list.jsx
- client/js/test_administration/components/exam_request_list/exam_request.jsx
- client/js/test_administration/components/exam_request_list/filter_tabs.jsx
- client/js/test_administration/components/exam_request_list/popup_menu.jsx
- client/js/test_administration/components/exam_request_list/schedule_form.jsx
things like sorting and filtering
> some of the little tweaks needed after demoing

- app/controllers/exports_controller.rb
- app/helpers/exam_export_helper.rb
- client/js/attendance/actions/attendance.js
- client/js/middleware/download.js
- client/js/test_administration/actions/exam_requests.js
- client/js/test_administration/components/exam_request_list/_exam_request_list.jsx
Changed it so that we can export with filenames now
> Worked with francisco to Refactor the download file/export middleware

- client/js/_exam_proctoring/components/exam_request_list/exam_request.jsx
- client/js/_exam_proctoring/components/exam_request_list/schedule_form.jsx
- client/js/_exam_proctoring/components/exam_request_list/schedule_form.spec.jsx
When the proctor goes to schedule an exam it auto generates the message that has the date and time. The message will also update if the proctor change the date or time before they click send. If the proctor deletes any part of the autogenerated message it will not update automatically anymore
> adds and auto updating auto generated message to the text area

- client/js/attendance/components/main/student_list.jsx
Fixes the screen reader issue mentioned in pivotal tracker ticket #139947529
> Don't render component unless it's needed

- app/controllers/exports_controller.rb
- app/helpers/attendance_exports_helper.rb
- spec/factories/attendances.rb
- spec/helpers/attendance_exports_helper_spec.rb
You can now export more than 10
> Fixing the attend export

- app/controllers/api/scorm_courses_controller.rb
- app/models/application_instance.rb
- app/models/registration.rb
- app/models/scorm_course.rb
- app/services/scorm_common_service.rb
- db/migrate/20170330122459_add_scorm_course_id_to_registration.rb
- db/migrate/20170330174948_add_course_user_index_to_registration.rb
- db/schema.rb
- lib/tasks/fix_scorm_course_id.rake
Add rake task to convert the integer values into strings with _
Add index for lms_course_id and lms_user_id lookup
Add foreign_key and primary key for relational lookup on registration and scorm_course.
Add class method to loop over all the ApplicationInstances and switch to that tenant.
> Change lms_course_id to a string and storing with the underscore

- app/controllers/api/scorm_courses_controller.rb
- app/models/registration.rb
- app/models/scorm_course.rb
- app/services/scorm_cloud_service.rb
- app/services/scorm_common_service.rb
- app/services/scorm_engine_service.rb
- db/migrate/20170331150221_change_scorm_cloud_id_on_scorm_course.rb
- db/schema.rb
- lib/tasks/fix_scorm_cloud_plain_id.rake
- lib/tasks/fix_scorm_course_id.rake
- spec/controllers/api/scorm_courses_controller_spec.rb
- spec/models/scorm_course_spec.rb
- spec/services/scorm_cloud_service_spec.rb
- spec/services/scorm_engine_service_spec.rb
As this can now refer to either scorm cloud or scorm engine.
Fix issue where scorm_service_id was getting coerced into an integer.
> Change scorm_cloud_id to scorm_service_id

- app/controllers/api/scorm_courses_controller.rb
Correctly follow the redirect to confirm with canvas and add it to the course.
> Fix file upload to store file in canvas

- app/helpers/scorm_course_helper.rb
- app/services/scorm_engine_service.rb
- config/initializers/rest_client.rb
Change resultsFormat to return FULL in the postback
Use interpolation for the urls
Add proxy setting to RestClient in an initializer
> Refactor scorm engine service to use RestClient

- app/controllers/api/scorm_courses_controller.rb
Currently, SCORM zips are open for anyone to view. I'm just adding a hidden tag so only the teacher can view it.
> Marks scorm file as hidden once uploaded

- app/controllers/api/attendances_controller.rb
- app/models/attendance.rb
- spec/controllers/api/attendances_controller_spec.rb
- spec/models/attendance_spec.rb
Use a first_or_create approach.
Only push into array if it isn’t destroyed.
Remove unused index method.
Add validation to attendance model for status.
Fix controller specs to actually test the create method.
Add model spec for attendance.
> Refactor attendance create method

- config/secrets.example.yml
- spec/controllers/api/exam_requests_controller_spec.rb
- spec/controllers/api/proctor_login_controller_spec.rb
- spec/factories/_common.rb
- spec/factories/exam_request.rb
- spec/models/exam_request_spec.rb
Add exam request controller specs
Add exam request model specs
Add proctor_login controller spec
> Add several rspecs

- .env.example
- app/services/scorm_engine_service.rb
- config/secrets.example.yml
- spec/controllers/scorm_courses_controller_spec.rb
- spec/services/scorm_engine_service_spec.rb
scorm_api_url -> scorm_api_path
scorm_ssl_domain -> scorm_url
scorm_domain -> scorm_url
> Refactor scorm engine variables

- app/models/scorm_course.rb
- client/js/scorm/components/analytics/analytic_list.jsx
- client/styles/scorm/analytics/partials/_index.scss
- Changes Average Score label to use the mean instead of median
- Makes the Student table sortable by name, passed, score, and time.
> Table sort

- app/controllers/scorm_courses_controller.rb
- app/models/registration.rb
- app/models/scorm_activity.rb
- app/services/scorm_common_service.rb
- app/services/scorm_engine_service.rb
Fix api to correctly parse depending if data is from cloud or engine
Improve before_actions to only run when appropriate
Fix tenant for scorm engine to correctly get set to course_id
Fix update_with to handle both cloud or engine data
Fix engine to create registration with correct password
> Fix engine postback

- app/controllers/scorm_courses_controller.rb
- app/services/scorm_common_service.rb
* Fix scorm engine postback issues
* Fixes to work with both cloud and engine data
* Fix grade writeback
* Fix scorm activities update to happen in a transaction
> Fix scorm engine postback

- app/services/scorm_engine_service.rb
- spec/services/scorm_engine_service_spec.rb
Send redirectOnExitUrl to launchLink request
Fix get request to send params in the header
> Fix SCORM redirect on exit

- client/js/attendance/components/main/student.jsx
- client/js/attendance/components/main/student_list.jsx
I am not sure if we need more than this.
> class names on icons

- app/controllers/omniauth_callbacks_controller.rb
- app/lib/lti/config.rb
- app/models/authentication.rb
- app/models/user.rb
- config/secrets.example.yml
- db/migrate/20170920214732_add_to_authentications.rb
- db/migrate/20170921201330_make_lti_user_id_unique.rb
- db/migrate/20170921202325_add_authentication_index.rb
- db/schema.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/lib/lti/config_spec.rb
- spec/models/authentication_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/support/omniauth.rb
> Merge upstream

- Gemfile
- Gemfile.lock
- app/models/application.rb
- config/environments/development.rb
- config/environments/production.rb
- db/migrate/20170922215453_add_que.rb
- db/schema.rb
Add public tenant to Application
> Add Que gem

- config/secrets.example.yml
ENV variables are not available in certain environments
> Fix secrets example

- Gemfile
- Gemfile.lock
- app/services/scorm_common_service.rb
- spec/services/scorm_cloud_service_spec.rb
- spec/services/scorm_engine_service_spec.rb
> Add gradebook writeback

- app/controllers/concerns/encryption_support.rb
- app/models/application_instance.rb
- app/models/authentication.rb
- app/models/registration.rb
- config/secrets.example.yml
* Treat keys as hex-encoded byte strings so that we can have a full 256 bits of entropy
* Update secret example
> Add Encryption Support

- app/models/registration.rb
- client/apps/scorm/components/scorm/courses_list.jsx
- client/apps/scorm/reducers/scorm.js
Fixes a few bugs with the UI/UX
> Cc scorm bugs

- app/controllers/api/proctor_conversations_controller.rb
use the url from site instead of the secrets
> Jd fix message

- .env.example
- config/initializers/nuclear_secrets.rb
- config/secrets.example.yml
- db/seeds.rb
Add canvas access token to secrets again
Fix seeds to find applications by key
> Update seeds to create app instances

- app/controllers/concerns/canvas_support.rb
- app/helpers/application_helper.rb
- app/views/shared/_default_admin_client_settings.html.erb
- app/views/shared/_default_client_settings.html.erb
Upstream code from https://github.com/atomicjolt/lti_starter_app/pull/142
> Update the oauth callback urls to accept a host with multiple subdomains

- client/apps/attendance/components/main/__snapshots__/student_list.spec.jsx.snap
- client/apps/attendance/components/main/student.jsx
- client/apps/attendance/components/main/student_list.jsx
- client/apps/attendance/components/main/student_list.spec.jsx
- client/apps/attendance/reducers/attendance.js
- client/apps/attendance/reducers/attendance.spec.js
- client/apps/attendance/reducers/student.js
- client/apps/attendance/styles/modules/_utility.scss
- client/apps/attendance/styles/partials/_index.scss
* Send appropriate student data to api
* Display processing or regular buttons
* Remove optimistic update of attendances unless it is to remove attendance
> Add a spinner to marking attendance

- db/migrate/20171023190624_add_index_to_attendance.rb
- db/schema.rb
For a course with 200 students
before:
after:
> Add index to Attendance database schema

- app/controllers/api/scorm_courses_controller.rb
- app/services/scorm_common_service.rb
- config/initializers/nuclear_secrets.rb
- config/secrets.example.yml
* Fixes adhesion to validate jwt with a shared token for scorm courses
* Fixes response to include package_id after uploading scorm package
> Validate shared auth jwt for scorm course create

- app/controllers/application_controller.rb
If the first param was NULL, then it would create a race condition.
> Fix sql race condition

- app/lib/adhesion/exceptions.rb
- app/services/scorm_engine_service.rb
- client/apps/scorm/reducers/scorm.js
* Raise SCORM 500 errors
* Move include ScormCommonService inside the class
* Display meaningful error text to user
* Appropriately raise exception if scorm engine throws an error
> Scorm error passthrough

- Gemfile
- Gemfile.lock
We can upgrade again when we go to rails 5.1
> Downgrade due to 0.13.1 for compatibility with rails 5.0

- app/services/scorm_engine_service.rb
Recursively load all the scorm courses from scorm engine.
> Load all scorm courses

- app/controllers/api/submissions_controller.rb
- app/lib/integrations/sis.rb
- app/models/sis_grade.rb
- client/apps/post_grades/components/post_grades.jsx
- client/apps/post_grades/components/post_grades/_post_grades.jsx
- client/apps/post_grades/components/post_grades/assignments.jsx
- client/apps/post_grades/components/post_grades/grade_types.jsx
- client/apps/post_grades/components/post_grades/sections.jsx
- client/apps/post_grades/reducers/assignments.js
- client/apps/post_grades/reducers/index.js
- client/apps/post_grades/reducers/sections.js
- client/apps/post_grades/reducers/sections_info.js
- client/apps/post_grades/reducers/submissions.js
- client/apps/post_grades/routes.jsx
- client/apps/post_grades/styles/partials/_index.scss
- client/libs/camelizer.js
- spec/controllers/api/submissions_controller_spec.rb
* Use forms
* Fix Grade book -> Gradebook
* Use moment.calendar() instead of spliting the date data
* Cancel will now cancel the confirm and then close modal if clicked twice.
* Use get_all in the canvas request to only make one request each.
* Add reducer for submissions
* Submit section metadata after submission succeeds
* Add to sections info reducer
* Close modal after section info succeeds
> Improve postgrades component

- app/controllers/api/scorm_courses_controller.rb
* Don’t use system, use exec instead
* Use Dir to mkdir
* Fork and call exec
* Do this as exec replaces the current process with what is called here
> Refactor handling scorm files

- client/apps/post_grades/components/post_grades/sections.jsx
A simple fix to change the drop down menu if there's only a single section in a course.
> Post Grades Tool: Single sections in a course

- client/apps/post_grades/components/post_grades/_post_grades.jsx
- client/apps/post_grades/components/post_grades/grade_types.jsx
- client/apps/post_grades/styles/partials/_index.scss
Require grade type to be selected before allowing form submit
> Fix grade push modal grade type selection

- app/controllers/api/submissions_controller.rb
Store grade and score in both cases of doing total or a specific assignment
> Fix grade push submission

- app/controllers/api/course_completions_controller.rb
- spec/controllers/api/course_completions_controller_spec.rb
Don’t limit course complete enrollments to 10 enrollments.
> Fix course completion for students with many enrollments

- app/lib/adhesion/exceptions.rb
- app/services/scorm_common_service.rb
- spec/services/scorm_cloud_service_spec.rb
- spec/services/scorm_engine_service_spec.rb
Send the response so we can see what is going on and why it errs.
> Improve scorm post lms grades errors

- app/controllers/api/atomic_docs_controller.rb
- app/models/atomic_doc_session.rb
- db/migrate/20190516003000_add_expires_at_to_atomic_doc_session.rb
- db/schema.rb
- spec/models/atomic_doc_session_spec.rb
> Expire Atomic Doc Sessions

- app/controllers/api/atomic_docs_controller.rb
- spec/controllers/api/atomic_docs_controller_spec.rb
Don't create an atomic doc, that is the job of the document upload endpoint.
> Fix create atomic doc session

- app/jobs/upload_canvas_job.rb
- app/services/scorm_engine_service.rb
No need for this extra layer, just use File.new
> Upload files without using UploadIO

- Gemfile
- Gemfile.lock
A new version was finally released that included the changes that were on the git ref.
> Update libreconv gem

- app/jobs/poll_canvas_upload_job.rb
- app/jobs/upload_canvas_job.rb
- app/jobs/wrapup_upload_canvas_job.rb
- app/lib/adhesion/exceptions.rb
- app/mailers/retry_mailer.rb
- app/views/retry_mailer/retry_email.html.erb
- app/views/retry_mailer/retry_email.text.erb
- spec/mailers/previews/retry_mailer_preview.rb
- spec/mailers/retry_mailer_spec.rb
Rescue a gateway timeout and check canvas every minute for 30 minutes until the file is in place.
> Handle gateway timeout better

- db/migrate/20190719163219_change_scorm_course_message_type.rb
- db/schema.rb
Don't limit to 2048 characters.
> Change scorm_course message to a text field

- app/jobs/upload_canvas_job.rb
Don't silently fail the GET request for the file id.
> Handle gateway timeout when finalizing an upload

- app/jobs/scorm_import_job.rb
- app/jobs/scorm_status_check_job.rb
If Rustici receives a read timed out from canvas, try importing again.
> Retry import scorm to rustici

- app/models/scorm_course.rb
- app/services/scorm_common_service.rb
- client/apps/scorm/reducers/scorm.js
Also fixes an issue where if the scorm tool is loaded before importing is complete, it would error.
> Display loader while scorm package is importing

- app/jobs/ims_import_job.rb
Allow ims import to update a scorm course. This will update the scorm course with the new data(title, score, etc) and also send the file to Rustici to be processed if it has changed or is new.
> Fix ims import to update scorm

- app/jobs/scorm_status_check_job.rb
Try again if the rate limit is hit.
> Handle rate limit error from Rustici Engine to Canvas

- RELEASE-NOTES.txt
- app/models/application.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/error.js
- client/apps/user_tool/app.jsx
- client/apps/user_tool/components/home.jsx
- client/apps/user_tool/components/layout/index.jsx
- client/apps/user_tool/components/layout/index.spec.jsx
- client/apps/user_tool/history.js
- client/apps/user_tool/middleware/api.js
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- client/apps/user_tool/reducers/error.js
- client/apps/user_tool/reducers/error.spec.js
- client/apps/user_tool/reducers/index.js
- client/apps/user_tool/routes.jsx
- client/apps/user_tool/store/configure_store.js
- client/apps/user_tool/styles/_defines.scss
- client/apps/user_tool/styles/modules/_all.scss
- client/apps/user_tool/styles/modules/_colors.scss
- client/apps/user_tool/styles/modules/_utility.scss
- client/apps/user_tool/styles/partials/_base.scss
- client/apps/user_tool/styles/partials/_index.scss
- client/apps/user_tool/styles/styles.less
- client/apps/user_tool/styles/styles.scss
- client/packs/user_tool.js
- db/seeds.rb
Pivotal Tracker: [#171524038](https://www.pivotaltracker.com/story/show/171524038)
This adds the user tool as an LTI tool to Adhesion.
It's adds a shell of the user tool client app and adds the user tool to the list of applications in `seeds.rb`.
The tool is configured to display in the account navigation for account admins.
> Add User Tool as LTI Tool

- db/seeds.rb
Mirror the user tool setup and set all the subdomains via the secrets.
> Set the domains from the secrets file, default to application setting

- client/apps/user_tool/components/main/__snapshots__/no_search_results.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/no_search_results.jsx
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
Just a few fixes. Please refer to the git commit messages for more details.
> A Few Small Fixes

- client/apps/user_tool/components/home.jsx
- client/apps/user_tool/styles/partials/_index.scss
Pivotal Tracker: [#172383707](https://www.pivotaltracker.com/story/show/172383707)
This will make it easier for users to see where they are.
> Add Application Title to Top of Page

- package.json
- yarn.lock
https://github.com/advisories/GHSA-p6mc-m468-83gw
> Update lodash for security patch

- Gemfile
- Gemfile.lock
We don't use these gems with our CI
> Remove pronto gems

- client/apps/docviewer/components/main/docviewer.jsx
Pivotal Tracker: [#177146138 - Default zoom should be fit-to-width](https://www.pivotaltracker.com/story/show/177146138)
These changes allow for page size to be determined by the current window size. Adjusting the browser window size will trigger `updateDimensions` which will scale and then re-render the page.
> Sb fit page width

- yarn.lock
Security patch to atomic-canvas package
> Update atomic-canvas package

- package.json
Somehow this was missing on the previous PR
> Update atomic-canvas package.json
