atomicjolt/adhesion

- Gemfile
- Gemfile.lock
- app/controllers/api/proctored_exams_controller.rb
- client/js/test_administration/components/exam_request_list/_exam_request_list.jsx
- client/js/test_administration/components/exam_request_list/_exam_request_list.spec.jsx
- client/js/test_administration/components/exam_request_list/new_proctor_code.jsx
- client/js/test_administration/components/exam_request_list/new_proctor_code.spec.jsx
- client/js/test_administration/reducers/exam_requests.js
- db/migrate/20170301203616_add_unlocked_by_id_and_name_to_exam_request.rb
- db/schema.rb
- db/seeds.rb
this does a few things:
- makes it so that if a proctor opens the app and doesnt have a proctor code it creates one for them
- when a proctor goes to unlock an exam it checks canvas for the proctor codes so we dont have to sync all the data to adhesion
> Get proctor code

- lib/tasks/shared_auth.rake
We no longer use lti_key for the tenant key.
> Fix shared_auth to use correct field of tenant.

- client/styles/attendance/partials/_index.scss
Before this, zooming(cmd +) would move the components but now they will stay in place.
> Fixing  zooming on attendance

- client/styles/attendance/partials/_index.scss
I've tested this on Chrome, Firefox, and Safari
> Fixed ui export dialog boxes being cut off

- app/services/scorm_engine_service.rb
Wait before getting title to the course to move on.
Use a backoff rather than always asking in a specific interval.
> Wait for scorm engine to finish processing.

- config/application.rb
This used to be included with rails/all but no longer is
> Add syslog/logger to application config

- app/models/application.rb
Using the 'admin' subdomain for authenticating via OAuth with Canvas.
> Use Admin for Auth

- app/controllers/api/attendances_controller.rb
- spec/controllers/api/attendances_controller_spec.rb
Refactor so not as many database hits happen
before refactoring api:
after refactoring api:
> Improve attendance creation/update

- Gemfile
- Gemfile.lock
- app/controllers/exports_controller.rb
- app/jobs/attendance_report_job.rb
- config/initializers/active_job.rb
- spec/jobs/attendance_report_job_spec.rb
This allows us to enqueue jobs without manually enqueueing them on the public tenant, the gem does it for us.
> Use apartment-activejob-que to assist with background jobs

- app/controllers/api/scorm_courses_controller.rb
- app/helpers/scorm_course_helper.rb
- app/jobs/scorm_import_job.rb
- app/jobs/scorm_status_check_job.rb
- app/jobs/upload_canvas_job.rb
- app/lib/adhesion/exceptions.rb
- app/models/scorm_course.rb
- app/services/scorm_common_service.rb
- app/services/scorm_engine_service.rb
- client/apps/scorm/actions/scorm.js
- client/apps/scorm/components/scorm/_scorm_index.jsx
- client/apps/scorm/reducers/scorm.js
- client/apps/scorm/reducers/scorm.spec.js
- config/initializers/nuclear_secrets.rb
- config/routes.rb
- config/secrets.example.yml
- db/migrate/20171211225415_add_import_job_status_to_scorm_course.rb
- db/schema.rb
- spec/controllers/api/scorm_courses_controller_spec.rb
- spec/models/scorm_course_spec.rb
* Add import_job_status to scorm_courses
* Add workers to upload scorm courses
* Don’t open the file so many times
* Add scorm course status route
* Copy upload into temp file to ensure it stays around after the web request goes away
* Update job status if something fails
* Add ability to poll scorm course import status
* Use a configurable storage mount
* Set the scorm_service_id correctly on creation
* Pass in lms_course_id when creating ScormCourse record
* Update replace scorm package to use background workers
> Improve SCORM uploads

- app/controllers/api/scorm_courses_controller.rb
- app/jobs/scorm_import_job.rb
- app/lib/adhesion/exceptions.rb
- config/initializers/rack.rb
- config/initializers/tmp_dir.rb
* Remove thread
* Shell out and make system commands to mv the temp file
* mv file into a `job/<scorm_course_id>/` dir
* Reduce the buffer from 100 MB to 1 MB
* Override Dir.tmpdir and append “tmp” to end of tmpdir in production
> Better scorm file uploads

- app/services/scorm_engine_service.rb
Allow RestClient to throw errors when the api it connects to returns 4XX and 5XX codes.
> Don’t use block with RestClient

- app/controllers/concerns/lti_support.rb
- app/controllers/omniauth_callbacks_controller.rb
This is to fix when adhesion sends emails to confirm account user on lti_launches.  This wasn't immediately evident when testing locally.  To test, enable emails on local machine and look at the log for the lti_launch to determine if devise is attempting to send a confirmation email.
add_to_role function commits user to database and sends confirmation email before calling skip_confirmation
> Adjust skip_confirmation before commiting User to database

- app/controllers/application_controller.rb
- app/mailers/error_mailer.rb
- spec/mailers/error_mailer_spec.rb
* Don’t try to serialize the uploaded file, just grab the headers and stick those into the error hash
* Enqueue ErrorMailer with json data and parse that json in the mailer
* Don’t let it try to serialize the data for us, we will handle the data instead.
> Fix error handling

- app/mailers/error_mailer.rb
- spec/mailers/error_mailer_spec.rb
Rails apparently requires this in production mode
We had hoped to let sendmail set this, but it doesn't look like
rails will allow that.
> Set the FROM to the same as the TO for sending error emails

- app/controllers/api/submissions_controller.rb
- client/apps/post_grades/actions/submissions.js
- client/apps/post_grades/components/post_grades/_post_grades.jsx
- client/apps/post_grades/components/post_grades/sections.jsx
- spec/controllers/api/submissions_controller_spec.rb
Get the gradetype using a document querySelector.
Change post to send gradetype instead of type for clarity.
Always display the All Sections and each section in the dropdown.
Update specs.
> Fix grade push on Edge browser

- app/controllers/api/submissions_controller.rb
Get all grades, not just first 10 students.
We will want to change this to get 100 at a time through a background job.
> Fix postgrades with more than 10 students

- client/apps/post_grades/components/post_grades/sections.jsx
Remove feature (#307) that only shows the one section if there is only one section.
We can add this back in later once the functionality can be fixed.
> Fix post grades all sections

- client/apps/course_completion/components/complete.jsx
This pull request changes the displayed text when placing the tool in the editor and when being viewed by an user enrollment not of the Student type.
> Display notice if User Enrollment cannot be ended

- app/controllers/api/course_completions_controller.rb
This pull request fixes a typo when checking for a valid enrollment.  Check for the single enrollment in the course to be nil rather than the potential array of enrollments.
> Typo when checking for nil Enrollment

- app/services/scorm_engine_service.rb
Return the 404 code instead of failing
> Don't fail when a delete request is sent and a 404 is returned

- app/jobs/upload_canvas_job.rb
Rather than create duplicate files, just overwrite.
This fixes a problem where the background worker attempts multiple times to upload a file to canvas and fails. We don't want that scorm_files directory bloated with hundreds of partial uploads.
> Fix SCORM to canvas file uploads

- app/models/user.rb
- app/services/scorm_common_service.rb
- db/migrate/20190214164316_add_context_id_to_registration.rb
- db/schema.rb
- spec/controllers/scorm_courses_controller_spec.rb
- spec/factories/_common.rb
- spec/services/scorm_cloud_service_spec.rb
- spec/services/scorm_engine_service_spec.rb
Only submit for students
This is backwards compatible with data (Registrations) created prior to this change. If a student launches a SCORM course and there isn't a context_id associated with their registration, it will then be associated. This context_id is used to determine if the user is a student in the course and only submit to the LMS if they are a student.
> Fix scorm packages to not submit to LMS for teachers.

- client/apps/scorm/reducers/scorm.js
This fixes a case where if the browser looses it's internet connection, then it would start polling for the status of id `undefined`.
> Fix polling for scorm status

- app/jobs/atomic_doc_job.rb
Instead of storing at `atomic_doc/<atomic_doc_id>`
Store at `atomic_docs/<lms_course_id>/<lms_file_id>/<atomic_doc_id>`
fail back to `atomic_docs/unknown/unknown/<atomic_doc_id>`
> Improve file storage location

- app/controllers/api/scorm_courses_controller.rb
Fixes the case where someone uploads tho same zip twice, and then deletes one of the scorm courses, and the zip getting deleted for the other scorm course. This ensures a 1 to 1 matching of scorm courses to zips within the same canvas course.
> Make each scorm zip upload unique

- app/jobs/upload_canvas_job.rb
- app/jobs/wrapup_upload_canvas_job.rb
If we get a read timeout while deleting or hiding a file, just ignore it.
> Handle Net::ReadTimeout from canvas

- db/seeds.rb
Pivotal Tracker: [#171580747](https://www.pivotaltracker.com/story/show/171580747)
We need to allow the user tool subdomain to be configurable so we can use our custom subdomain in production.
We still want the subdomain to default to `usertool` if a custom one isn't specified.
We need to add the custom subdomain to the cluster setup as described in [Pivotal Tracker #171579729](https://www.pivotaltracker.com/story/show/171579729).
> Update Seeds to Allow a Custom Subdomain for the User Tool

- db/seeds.rb
By adding `presence`, we'll only use the value in `secrets.user_tool_subdomain` if it is present. This will avoid using an empty string which someone might conceivably set `user_tool_subdomain` to.
``` ruby
nil.presence || Application::USERTOOL
=> "usertool"
" ".presence || Application::USERTOOL
=> "usertool"
"123".presence || Application::USERTOOL
=> "123"
```
> Improve Subdomain Check

- db/seeds.rb
Pivotal Tracker: [#171727406](https://www.pivotaltracker.com/story/show/171727406)
All of the other items in the Canvas nav are nouns, so we want to mirror that.
> Update Menu Title from "Manage Users" to "User Management"

- app/controllers/api/canvas_users_controller.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/home.jsx
- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/user_search_result.spec.jsx.snap
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- client/apps/user_tool/components/main/user_search_result.jsx
- client/apps/user_tool/components/main/user_search_result.spec.jsx
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- config/routes.rb
- db/seeds.rb
Pivotal Tracker: [#171524287](https://www.pivotaltracker.com/story/show/171524287), [#171524862](https://www.pivotaltracker.com/story/show/171524862), [#171524339](https://www.pivotaltracker.com/story/show/171524339)
This adds an initial, rudimentary search page. It allows you to search for a student and displays the 
first page of results. It's missing things such as the ability to page through other results and displaying all of the necessary user information.
I'd written enough code that I wanted to get it reviewed before going farther.
[Search Page](https://pull-request-demo-files.s3-us-west-2.amazonaws.com/search_page.mp4)
> Add Search Page

- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
Pivotal Tracker: [#171864889](https://www.pivotaltracker.com/story/show/171864889)
The [Canvas API endpoint](https://canvas.instructure.com/doc/api/users.html#method.users.api_index) we're using to search requires that the `search_term` parameter be at least 3 characters. It returns a `400 Bad Request` if you send less than 3.
This branch enforces that constraint on the front-end.
[Search Term Length Constraint](https://pull-request-demo-files.s3-us-west-2.amazonaws.com/search_term_length_constraint.mp4)
> Add Search Length Constraint

- Gemfile
- Gemfile.lock
Our Gemfile doesn't specify a version of Rubocop, but our Hound configuration specifies `0.75.0`. I think we should set them to the same version so we don't run into compatibility issues.
I, for example, couldn't run Rubocop locally because our `.rubocop.yml` config raises an error in the current version fo Rubocop.
> Set Rubocop in Gemfile to Match Hound Config

- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
Pivotal Tracker: [#171634698](https://www.pivotaltracker.com/story/show/171634698)
After more testing, it looks like the [list users in account](https://canvas.instructure.com/doc/api/users.html#method.users.api_index) endpoint already includes users from child sub-accounts, so we won't have to do anything ourselves to make that work.
This removes the `include_sub_accounts` parameter since it's not necessary.
I added this parameter when I was originally writing the action, and I planned on adding support for it in the `CanvasUsersController` later. I never updated the controller though because I realized we didn't need it.
> Remove Unnecessary `include_sub_accounts` Param

- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
In Firefox, things work fine without calling `event.preventDefault()`. In Chrome, Safari and Edge though, clicking the "Search" button submits an invalid "GET" request to the server which returns a 401 Unauthorized and the application crashes.
Adding `event.preventDefault()` prevents that invalid request. Adding `event.target.form.reportValidity()` triggers the native browser form validation which lets the user know if their search term is valid or not. Before adding `event.preventDefault()` the form validation happened automatically. Now, we have to call it explicitly.
I'm not a fan of calling `event.preventDefault()` when I can avoid it, but I don't know of a better solution here.
**Before**
**After**
> Prevent Form Submission When Clicking the "Search" Button

- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/user_search_result.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- client/apps/user_tool/components/main/user_search_result.jsx
- client/apps/user_tool/components/main/user_search_result.spec.jsx
Pivotal Tracker: [#171524370](https://www.pivotaltracker.com/story/show/171524370)
This adds a modal for editing users. The modal is activated by clicking on the name of a user in the search results. The modal doesn't actually allow you to edit the user yet; that will be added later.
This implementation renders a separate edit modal for each of the users displayed in search results.
I considered rendering a single edit modal to be used for all of the displayed users; that seemed to be cleaner as far as the DOM is concerned. Rendering a modal for each user seemed to simplify the code though, and that seems more valuable. Also, rendering a separate modal for each entity seems to be the pattern we use elsewhere in our applications.
> Add Edit User Modal

- app/controllers/api/canvas_users_controller.rb
- app/controllers/concerns/canvas_support.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- client/common/components/common/__snapshots__/pagination.spec.jsx.snap
- client/common/components/common/pagination.jsx
- client/common/components/common/pagination.spec.jsx
- spec/controllers/api/canvas_users_controller_spec.rb
- spec/controllers/concerns/canvas_support_spec.rb
- spec/support/webmock_requests.rb
Pivotal Tracker: [#171680475](https://www.pivotaltracker.com/story/show/171680475)
This branch adds pagination for the search results. It allows a user to move to the next and previous pages of results when they're available.
This uses the default page size from the Canvas API which is currently 10. If we wanted to add more results, it would be trivial to alter that number.
We discussed at some length the possibility of providing more sophisticated pagination that allows the user to do things like jump to the first and last pages and see the total number of pages. Ultimately, we decided to stick with this basic next/previous implementation because it seems sufficient and the more sophisticated version didn't seem like it was worth the development time.
Our conversation concerning this can …
> Add Pagination for Search Results

- app/controllers/api/canvas_users_controller.rb
- spec/controllers/api/canvas_users_controller_spec.rb
- spec/support/webmock_requests.rb
Pivotal Tracker: [#171825565](https://www.pivotaltracker.com/story/show/171825565)
This updates the API call to Canvas to include user emails. This will allow us to display the user email on the search results page and in the edit modal.
We didn't fetch them previously because I didn't realize you could pass an `include` param to the [List users in account](https://canvas.instructure.com/doc/api/users.html#method.users.api_index) endpoint to request user emails. I was thinking we'd have to make a separate API call.
> Include User Emails When Fetching Account Users

- app/controllers/api/canvas_users_controller.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/user_search_result.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- client/apps/user_tool/components/main/user_search_result.jsx
- client/apps/user_tool/components/main/user_search_result.spec.jsx
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- config/routes.rb
- spec/controllers/api/canvas_users_controller_spec.rb
Pivotal Tracker: [#171524491](https://www.pivotaltracker.com/story/show/171524491), [#171525027](https://www.pivotaltracker.com/story/show/171525027)
This adds a modal and form that allows an admin to update the following information for a user:
- Name
- Login ID
- Password 
- SIS ID
- Email
For a couple of the API calls to Canvas, I used `canvas_api.api_put_request` instead of `canvas_api.proxy`. I generally prefer using `proxy`, but it wasn't working for those 2 API calls for whatever reason. I'd like to figure out what the issues were, but I didn't want to let it hold up adding this code.
When we update the name, the sortable name is updated automatically, but the display name (AKA short name) is not. Should we update the display name too?
With this implementation, when we update the …
> Add Edit User Form

- client/apps/user_tool/components/main/__snapshots__/no_search_results.spec.jsx.snap
- client/apps/user_tool/components/main/__snapshots__/search_page.spec.jsx.snap
- client/apps/user_tool/components/main/no_search_results.jsx
- client/apps/user_tool/components/main/no_search_results.spec.jsx
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- client/apps/user_tool/components/main/start_searching.jsx
Pivotal Tracker: [#171942592](https://www.pivotaltracker.com/story/show/171942592)
This branch adds a couple of components to match [Brandon's designs](https://xd.adobe.com/view/fc7bb54f-3fa8-4a42-7f0d-160d08c990b3-8a4a/grid).
One component is displayed when the user first loads the application:
The other component is displayed when the user performs a search that returns no results:
> Add No Results Components

- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
Pivotal Tracker: [#172228616](https://www.pivotaltracker.com/story/show/172228616)
Currently, the password field in the edit user form is labeled with "Password". Brandon suggested "New Password" would be better because it doesn't display the old password; it's just a field to change it.
> Improve Password Input Label

- app/controllers/api/canvas_account_users_controller.rb
- app/controllers/concerns/jwt_token.rb
- app/helpers/jwt_helper.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- config/routes.rb
- db/seeds.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
- spec/controllers/concerns/jwt_token_spec.rb
Pivotal Tracker: [#172031298](https://www.pivotaltracker.com/story/show/172031298)
Previously, the client specified which Canvas account they wanted to operate within by passing the ID of the account in the url. e.g. `/canvas_accounts/123/canvas_users`. Allowing the client to specify which Canvas account they want to use creates a security risk though; someone could manually create a request to the back-end and access accounts they wouldn't otherwise have permission to access.
To ensure admins are only accessing users they have permissions to access, we're using the Canvas account ID we get in the LTI launch instead.
I added additional code to store the Canvas account ID in the JWT during the LTI launch.
I renamed the `canvas_accounts/:account_id/canvas_users` endpoint to …
> Prevent Admins From Listing and Updating Users Outside Their Account

- app/controllers/api/canvas_account_users_controller.rb
- app/models/canvas_user_change.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- db/migrate/20200409204253_create_canvas_user_changes.rb
- db/migrate/20200414192353_add_failed_attributes_to_canvas_user_changes.rb
- db/schema.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
- spec/factories/canvas_user_changes.rb
- spec/models/canvas_user_change_spec.rb
Pivotal Tracker: [#171524499](https://www.pivotaltracker.com/story/show/171524499)
This branch adds logging for changes to Canvas user data. When someone attempts to change user data, a record in the database is created specifying the data being changed and who is changing it. This record is created whether or not the request succeeds and the changes are actually applied.
The method that creates the logging record for the user change raises an exception if the record is invalid. I think this makes sense because we're using this method to log changes to sensitive user data. If the record is invalid and the logging record isn't created, we want to know about it.
Here are a couple of examples of how the database records look:
**Success**
**Partial Success**
> Log Changes to User Data

- client/apps/user_tool/styles/partials/_inputs.scss
This should break any long words, emails, etc before they overflow their container.
> Was: overflow fix

- client/apps/user_tool/components/main/__snapshots__/user_search_result.spec.jsx.snap
- client/apps/user_tool/components/main/user_search_result.jsx
- client/apps/user_tool/components/main/user_search_result.spec.jsx
This should have been removed in #407 when we removed roles from the search page component. I made a mistake though and forgot to remove it from here.
> Remove Roles Table Cell From User Search Results

- app/controllers/api/canvas_account_users_controller.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
Pivotal Tracker: [#171524424](https://www.pivotaltracker.com/story/show/171524424)
We concluded that the most secure way to handle updating admin users was to just not do it. This branch adds a check to determine if the user being updated is an admin an any account in Canvas. If they are, we return a 401 Unauthorized instead of updating them.
To determine if the user being updated is an admin somewhere, we call the [List accounts](https://canvas.instructure.com/doc/api/accounts.html#method.accounts.index) endpoint. The docs for that endpoint state, "Typically, students and even teachers will get an empty list in response, only account admins can view the accounts that they are in." If we get a non-empty response from the endpoint, we assume the user being edited is an admin in some …
> Prevent Editing of Admin Users

- app/controllers/api/canvas_account_users_controller.rb
- app/models/canvas_user_change.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- client/apps/user_tool/styles/partials/_index.scss
- db/migrate/20200417204937_remove_password_from_canvas_user_changes.rb
- db/schema.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
- spec/factories/canvas_user_changes.rb
- spec/models/canvas_user_change_spec.rb
Pivotal Tracker: [#172383677](https://www.pivotaltracker.com/story/show/172383677)
In our demo meeting on April 17th, it was generally agreed that providing the ability to change a user's password presented a number of unacceptable security concerns.
This branch removes the ability to change a user's password. AU will instead use our tool to update a user's email if necessary and then instruct the student to use the standard Canvas password reset procedure.
I deleted a bunch of stuff. Look at all that red. Ain't it beautiful.
**Before**
**Without Password Field**
**After**
> Remove the Ability to Change a User's Password

- client/apps/user_tool/components/main/search_page.jsx
- client/apps/user_tool/components/main/search_page.spec.jsx
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- client/apps/user_tool/styles/styles.scss
Pivotal Tracker: [#172251053](https://www.pivotaltracker.com/story/show/172251053), [#172251090](https://www.pivotaltracker.com/story/show/172251090)
This branch adds loading indicators that are displayed while a search request is executing or while an update request is executing.
We also plan on adding a flash message indicating when a user is updated successfully, but that will happen in a separate pull request.
The loader I used is pretty basic. I used it because it was already in the project and it suits our purposes well enough. If we want to use a fancier Atomic Jolt loader; we could switch to that, but I wasn't sure it was worth the effort
> Add Loading Indicators

- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
It isn't strictly necessary that these values have defaults because `undefined` works just as well as `false` for how we're using them, but I think it's clearer to define all of the default state up front.
> Add Missing Default Application State

- app/models/canvas_user_change.rb
- spec/models/canvas_user_change_spec.rb
This updates the `CanvasUserChange` model to only include an attribute in the `failed_attributes` list if the new value for that attribute was different from the original value. This will improve consistency between the `failed_attributes` list and the individual attribute fields; the individual attribute fields are only populated if the value is changed.
With the previous implementation, you could have `NULL` in an individual attribute field but then see that attribute in the `failed_attributes` list. 
This would happen in a scenario where the API request to Canvas to update that certain attribute failed, but the attribute wasn't changed. So the attribute was included in the `failed_attributes` list but the individual attribute field was left blank because the value didn't change. I find …
> Improve Canvas User Change Logging

- app/controllers/api/canvas_account_users_controller.rb
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
- client/apps/user_tool/components/main/edit_user_modal.spec.jsx
- client/apps/user_tool/reducers/application.js
- client/apps/user_tool/reducers/application.spec.js
- client/apps/user_tool/reducers/success_messages.js
- client/apps/user_tool/reducers/success_messages.spec.js
- client/apps/user_tool/styles/partials/_errors.scss
- client/apps/user_tool/styles/partials/_inputs.scss
- client/apps/user_tool/styles/partials/_modal.scss
- config/routes.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
Pivotal Tracker: [#172383513](https://www.pivotaltracker.com/story/show/172383513)
Right now, we don't allow editing account admins. If someone tries to edit an account admin, the request is rejected on the back-end and an error message is returned. A better user experience would be to prevent the user from submitting the edit form for an account admin in the first place. This branch adds that functionality. 
In order to determine whether or not a given user is an account admin, I added a `show` action to the `CanvasAccountUsers` controller. I considered adding an `is_user_account_admin` action or something like that to the controller. Adding a `show` action seemed more predictable and user friendly to me though. It's certainly more RESTful.
To display the error message for admin users, …
> Disable Edit User Form for Account Admins

- client/apps/user_tool/components/layout/__snapshots__/errors.spec.jsx.snap
- client/apps/user_tool/components/layout/__snapshots__/success_messages.spec.jsx.snap
- client/apps/user_tool/components/layout/errors.jsx
- client/apps/user_tool/components/layout/errors.spec.jsx
- client/apps/user_tool/components/layout/success_messages.jsx
- client/apps/user_tool/components/layout/success_messages.spec.jsx
- client/apps/user_tool/components/main/__snapshots__/edit_user_modal.spec.jsx.snap
- client/apps/user_tool/components/main/edit_user_modal.jsx
Pivotal Tracker: [#172295926](https://www.pivotaltracker.com/story/show/172295926)
This branch adds aria-live announcements for error messages, success messages and the confirmation message in the edit user modal.
The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) state, "Assistive technologies will announce dynamic changes in the content of a live region. The live region must first be present (and usually empty), so that the browser and assistive technologies are aware of it. Any subsequent changes are then announced."
That's why, in each case, I arranged the code so there was always a node in the DOM with the `aria-live` attribute even if the node was empty.
**Confirmation Message and Success Message**
**Error Message**
> Add aria-live Announcements

- app/controllers/api/canvas_account_users_controller.rb
- app/models/canvas_user_change.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
- spec/models/canvas_user_change_spec.rb
Pivotal Tracker: [#172477006](https://www.pivotaltracker.com/story/show/172477006)
When updating a user, we make multiple API requests to Canvas to update the various pieces of user data that the tool allows you to update. However, if, for example, you only want to update the name of a user, there are a couple of API requests that are unnecessary because they're for updating other user data.
This branch updates the logic in the `CanvasAccountUsersController` `update` action to only make those API calls when necessary. These changes have the potential to eliminate up to 2 of the 5 Canvas API calls made in the update action. (Technically, it could eliminate 3 calls, but that would only happen if none of the user data was changed. I don't see why that would occur during normal usage of the …
> Eliminate Unnecessary Canvas API Calls

- app/controllers/concerns/lti_support.rb
- app/controllers/lti_launches_controller.rb
- spec/controllers/concerns/lti_support_spec.rb
Pivotal Tracker: [#172182759](https://www.pivotaltracker.com/story/show/172182759)
If the launching user is not an LTI admin in the current context, we want to reject the LTI launch for the user tool.
The user tool is only intended to be used by account admins.
This branch adds a `before_action` to the LTI launch to verify if the user is an LTI admin when the user tool is being launched. If the user is not an admin in the account the tool is being launched from, they'll see an error page and the LTI request will return a `401 Unauthorized`.
To be clear, the user tool is not visible in the account menu unless the user is an account admin. To get to the tool, a non-admin would have to acquire the direct link somehow.
Non-admins will see the following:
> Only Allow LTI Admins to Launch the User Tool

- app/controllers/api/canvas_account_users_controller.rb
- spec/controllers/api/canvas_account_users_controller_spec.rb
Pivotal Tracker: [#172592283](https://www.pivotaltracker.com/story/show/172592283)
The Canvas API docs for the [List users in account](https://canvas.instructure.com/doc/api/users.html#method.users.api_index) endpoint for the `search_term` parameter state, "Note that the API will prefer matching on canonical user ID if the ID has a numeric form. It will only search against other fields if non-numeric in form, or if the numeric value doesn't yield any matches." But that doesn't appear to be the case in my testing. I added the ID of one user to the name of another user and it pulled up both users when I searched using that ID.
There are a couple of places in the `CanvasAccountUsersController` where we search for users by ID when we want a specific user. Searching for users with their ID …
> Remove Searching by User ID

- client/apps/user_tool/styles/partials/_inputs.scss
Safari treats type="search" differently for some reason so these few lines of code fix that.
> safari search fix

- RELEASE-NOTES.txt
- app/controllers/application_controller.rb
Don't send an email for a routing error. Just display the 404 page.
> Adjust error handling for routing error

- RELEASE-NOTES.txt
- client/apps/user_tool/actions/application.js
- client/apps/user_tool/actions/application.spec.js
Pivotal Tracker: [#171524339](https://www.pivotaltracker.com/story/show/171524339)
We observed a bug where search terms with a "+" character in them weren't returning any results from the Canvas API even though there were users that matched the search term.
The problem was that the plus sign was being sent to our back-end as a space character instead of a literal plus sign. This search term with a space instead of a plus was then sent to the Canvas API and there were no matching results.
By URI encoding the search term before sending it to our back-end, we get the results we expect.
I also tested searching with a number of other special characters (~, !, /, #, ?, etc.) and they all worked fine.
> Fix Search Bug in User Tool

- RELEASE-NOTES.txt
- client/apps/user_tool/actions/application.js
We're having problems in the AU staging environment where requests are taking longer than 20 seconds and are timing out so the user can't perform certain actions. Increasing the timeout to 60 seconds won't improve the slow performance obviously, but it will at least prevent requests from timing out and will allow the user to use the application normally (albeit slowly).
> Increase Client-side Network Timeout

- app/helpers/scorm_course_helper.rb
- app/services/scorm_cloud_service.rb
- app/services/scorm_common_service.rb
- app/services/scorm_engine_service.rb
- spec/services/scorm_engine_service_spec.rb
If something glitches during the initial registration with Rustici, that launch is forever orphaned. This fixes it so if the registration is not present while launching the course, it will get created.
> Ensure Rustici engine has student registration

- app/views/layouts/errors.html.erb
No need to have our logo on the error page.
> Remove Atomic Jolt logo from error pages

- app/controllers/application_controller.rb
This leaks information about our server that could be a potential security risk. For example it leaks specific information about library versions we use. If a bad actor knows this information, they could use that to their advantage to attack the service.
For example, this error:
```
404 Not Found
/var/adhesion-gems/ruby/2.5.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
/var/adhesion-gems/ruby/2.5.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/var/adhesion-gems/ruby/2.5.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
/var/adhesion-gems/ruby/2.5.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
/usr/lib/ruby/2.5.0/net/http.rb:910:in `start' …
```
> Stop leaking gems in backtrace for errors

- client/apps/docviewer/components/main/annotation_controls.jsx
- client/apps/docviewer/components/main/document_controls.jsx
- client/apps/docviewer/components/main/docviewer.jsx
- package.json
- yarn.lock
Pivotal Tracker:
- [#176577175 - Full screen does not work within speed grader](https://www.pivotaltracker.com/story/show/176577175)
Fixes to enable fullscreen mode in canvas's speedgrader. Since the app is placed within an iframe, react-fullscreen-screen would try to access the wrong document. I had to broadcast a message to the global javascript which handles the rendering in full screen.
> Fix fullscreen mode to work within speedgrader

- Gemfile
- Gemfile.lock
Que was accidentally upgraded to 1.0.0 and we can't support 1.0.0 currently.
> Downgrade que to 0.14.3
